import { WorkItem } from '../types/work';

// Immagini e video placeholder
const IMG = (w: number, h: number) => `https://picsum.photos/${w}/${h}?random=${Math.floor(Math.random()*10000)}`;
const VIDEO = 'https://www.w3schools.com/html/mov_bbb.mp4';

export const mockWorks: WorkItem[] = [
  // Commercial
  {
    id: 'w1',
    slug: 'cantina-colle-petrito-xii',
    title: 'Cantina Colle Petrito: XII - Dodicesimo',
    shortDesc: 'Commercial',
    category: 'Branded',
    thumbnailUrl: IMG(800, 500),
    coverVideoUrl: VIDEO,
    description: 'Commercial per Cantina Colle Petrito che celebra il dodicesimo anniversario.',
    crew: [
      { role: 'Cliente', name: 'Cantina Colle Petrito' },
      { role: 'Produzione', name: 'Bekboard Studio' },
      { role: 'Fotografia', name: 'Pietro Giocondo' },
      { role: 'Montaggio', name: 'Pietro Giocondo' },
    ],
    backstageImages: [IMG(1200, 800), IMG(1200, 800), IMG(1200, 800)],
  },
  {
    id: 'w2',
    slug: 'luce-di-memoria-faro-minervino',
    title: 'Luce di memoria: restauro del Faro di Minervino Murge',
    shortDesc: 'Docufilm commerciale',
    category: 'Branded',
    thumbnailUrl: IMG(800, 500),
    coverVideoUrl: VIDEO,
    description: 'Docufilm commerciale sul restauro del Faro di Minervino Murge.',
    crew: [
      { role: 'Cliente', name: 'EdilVerde SRL' },
      { role: 'Produzione', name: 'Bekboard Studio' },
      { role: 'Scritto da', name: 'Pietro Giocondo e Gioacchino Bruno' },
      { role: 'Diretto da', name: 'Pietro Giocondo' },
      { role: 'Fotografia', name: 'Pietro Giocondo' },
      { role: 'Ass. fotografia', name: 'Angelo Preziusi' },
      { role: 'Montaggio', name: 'Pietro Giocondo' },
    ],
    backstageImages: [IMG(1200, 800), IMG(1200, 800), IMG(1200, 800)],
  },
  {
    id: 'w3',
    slug: 'minervino-murge-balcone-puglie',
    title: 'Minervino Murge: il balcone delle Puglie',
    shortDesc: 'Commercial',
    category: 'Branded',
    thumbnailUrl: IMG(800, 500),
    coverVideoUrl: VIDEO,
    description: 'Commercial per il Comune di Minervino Murge che mostra la bellezza del territorio.',
    crew: [
      { role: 'Cliente', name: 'Comune di Minervino Murge' },
      { role: 'Produzione', name: 'Bekboard Studio' },
      { role: 'Scritto da', name: 'Pietro Giocondo' },
      { role: 'Diretto da', name: 'Pietro Giocondo' },
      { role: 'Fotografia', name: 'Pietro Giocondo' },
      { role: 'Ass. fotografia', name: 'Angelo Preziusi' },
      { role: 'Montaggio', name: 'Pietro Giocondo' },
    ],
    backstageImages: [IMG(1200, 800), IMG(1200, 800)],
  },

  // Music Videos
  {
    id: 'w4',
    slug: 'nicolo-balducci-anna-paradiso-als-luise',
    title: 'Nicolò Balducci & Anna Paradiso - Als Luise die Briefe… W. A. Mozart',
    shortDesc: 'Music video',
    category: 'Music Video',
    thumbnailUrl: IMG(800, 500),
    trailerUrl: VIDEO,
    description: 'Videoclip musicale con Nicolò Balducci e Anna Paradiso per BIS Records.',
    crew: [
      { role: 'Con', name: 'Nicolò Balducci, Anna Paradiso, Francesca Giuliano' },
      { role: 'Client', name: 'BIS Records' },
      { role: 'Produzione', name: 'Bekboard Studio' },
      { role: 'Scritto da', name: 'Gioacchino Bruno' },
      { role: 'Diretto da', name: 'Gioacchino Bruno' },
      { role: 'Fotografia', name: 'Pietro Giocondo' },
      { role: 'Ass. fotografia', name: 'Angelo Preziusi' },
      { role: 'Make Up & Hair Stylist', name: 'Enza Gravina' },
      { role: 'Montaggio', name: 'Pietro Giocondo' },
    ],
    backstageImages: [IMG(1200, 800), IMG(1200, 800), IMG(1200, 800)],
  },
  {
    id: 'w5',
    slug: 'nicolo-balducci-anna-paradiso-mermaids-song',
    title: 'Nicolò Balducci & Anna Paradiso - The Mermaid\'s Song, Haydn',
    shortDesc: 'Music video',
    category: 'Music Video',
    thumbnailUrl: IMG(800, 500),
    trailerUrl: VIDEO,
    description: 'Videoclip musicale con atmosfere marine per BIS Records.',
    crew: [
      { role: 'Con', name: 'Nicolò Balducci, Francesco Volpe, Mariacristina Santomauro' },
      { role: 'Client', name: 'BIS Records' },
      { role: 'Produzione', name: 'Bekboard Studio' },
      { role: 'Scritto da', name: 'Gioacchino Bruno' },
      { role: 'Diretto da', name: 'Gioacchino Bruno' },
      { role: 'Fotografia', name: 'Pietro Giocondo' },
      { role: 'Ass. fotografia', name: 'Angelo Preziusi' },
      { role: 'Body Painter & Make Up', name: 'Serenza Castrovilli' },
      { role: 'Costume Supervisor & Hair Stylist', name: 'Francesca Giuliano' },
      { role: 'Mermaid Hair Stylist', name: 'Beatrice Cicchelli' },
      { role: 'Montaggio', name: 'Pietro Giocondo' },
    ],
    backstageImages: [IMG(1200, 800), IMG(1200, 800)],
  },
  {
    id: 'w6',
    slug: 'carlotta-dalia-pagina-romantica',
    title: 'Carlotta Dalia - Carlos Pedrell: Página Romántica',
    shortDesc: 'Music video',
    category: 'Music Video',
    thumbnailUrl: IMG(800, 500),
    trailerUrl: VIDEO,
    description: 'Videoclip musicale con Carlotta Dalia per Berlin Classics.',
    crew: [
      { role: 'Con', name: 'Carlotta Dalia' },
      { role: 'Client', name: 'Berlin Classics' },
      { role: 'Produzione', name: 'Bekboard Studio' },
      { role: 'Scritto e diretto da', name: 'Gioacchino Bruno e Pietro Giocondo' },
      { role: 'Fotografia', name: 'Pietro Giocondo' },
      { role: 'Montaggio', name: 'Pietro Giocondo' },
    ],
    backstageImages: [IMG(1200, 800), IMG(1200, 800)],
  },
  {
    id: 'w7',
    slug: 'carlotta-dalia-fantasia-sevillana',
    title: 'Carlotta Dalia - Joaquin Turina: Fantasia Sevillana',
    shortDesc: 'Music video',
    category: 'Music Video',
    thumbnailUrl: IMG(800, 500),
    trailerUrl: VIDEO,
    description: 'Videoclip musicale con Carlotta Dalia per Berlin Classics.',
    crew: [
      { role: 'Con', name: 'Carlotta Dalia' },
      { role: 'Client', name: 'Berlin Classics' },
      { role: 'Produzione', name: 'Bekboard Studio' },
      { role: 'Scritto e diretto da', name: 'Gioacchino Bruno e Pietro Giocondo' },
      { role: 'Fotografia', name: 'Pietro Giocondo' },
      { role: 'Montaggio', name: 'Pietro Giocondo' },
    ],
    backstageImages: [IMG(1200, 800), IMG(1200, 800)],
  },
  {
    id: 'w8',
    slug: 'carlotta-dalia-anecdotas-segovia',
    title: 'Carlotta Dalia - Andrés Segovia: 5 Anecdotas: 1. Allegretto',
    shortDesc: 'Music video',
    category: 'Music Video',
    thumbnailUrl: IMG(800, 500),
    trailerUrl: VIDEO,
    description: 'Videoclip musicale con Carlotta Dalia per Berlin Classics.',
    crew: [
      { role: 'Con', name: 'Carlotta Dalia' },
      { role: 'Client', name: 'Berlin Classics' },
      { role: 'Produzione', name: 'Bekboard Studio' },
      { role: 'Scritto e diretto da', name: 'Gioacchino Bruno e Pietro Giocondo' },
      { role: 'Fotografia', name: 'Pietro Giocondo' },
      { role: 'Montaggio', name: 'Pietro Giocondo' },
    ],
    backstageImages: [IMG(1200, 800), IMG(1200, 800)],
  },
  {
    id: 'w9',
    slug: 'carlotta-dalia-nicolo-balducci-passacaglia',
    title: 'Carlotta Dalia & Nicolò Balducci perform "Passacaglia della Vita" by Stefano Landi',
    shortDesc: 'Music video',
    category: 'Music Video',
    thumbnailUrl: IMG(800, 500),
    trailerUrl: VIDEO,
    description: 'Videoclip musicale con Carlotta Dalia e Nicolò Balducci.',
    crew: [
      { role: 'Con', name: 'Carlotta Dalia e Nicolò Balducci' },
      { role: 'Produzione', name: 'Bekboard Studio' },
      { role: 'Scritto e diretto da', name: 'Gioacchino Bruno e Pietro Giocondo' },
      { role: 'Fotografia', name: 'Pietro Giocondo' },
      { role: 'Ass. fotografia', name: 'Angelo Preziusi' },
      { role: 'Montaggio', name: 'Pietro Giocondo' },
    ],
    backstageImages: [IMG(1200, 800), IMG(1200, 800)],
  },
  {
    id: 'w10',
    slug: 'carlotta-dalia-nicolo-balducci-dream-with-me',
    title: 'Carlotta Dalia & Nicolò Balducci perform "Dream With Me" by Leonard Bernstein',
    shortDesc: 'Music video',
    category: 'Music Video',
    thumbnailUrl: IMG(800, 500),
    trailerUrl: VIDEO,
    description: 'Videoclip musicale con Carlotta Dalia e Nicolò Balducci.',
    crew: [
      { role: 'Con', name: 'Carlotta Dalia e Nicolò Balducci' },
      { role: 'Produzione', name: 'Bekboard Studio' },
      { role: 'Scritto e diretto da', name: 'Gioacchino Bruno e Pietro Giocondo' },
      { role: 'Fotografia', name: 'Pietro Giocondo' },
      { role: 'Ass. fotografia', name: 'Angelo Preziusi' },
      { role: 'Montaggio', name: 'Pietro Giocondo' },
    ],
    backstageImages: [IMG(1200, 800), IMG(1200, 800)],
  },

  // Cortometraggio
  {
    id: 'w11',
    slug: 'hai-riso-cortometraggio',
    title: 'Hai riso?',
    shortDesc: 'Cortometraggio',
    category: 'Altri',
    thumbnailUrl: IMG(800, 500),
    coverVideoUrl: VIDEO,
    description: 'Cortometraggio con Giuliana Stancarone e Francesco Volpe.',
    crew: [
      { role: 'Con', name: 'Giuliana Stancarone, Francesco Volpe' },
      { role: 'Produzione', name: 'Bekboard Studio' },
      { role: 'Scritto da', name: 'Gioacchino Bruno e Giuseppe Cassano' },
      { role: 'Diretto da', name: 'Giuseppe Cassano' },
      { role: 'Aiuto regia', name: 'Gioacchino Bruno' },
      { role: 'Fotografia', name: 'Pietro Giocondo' },
      { role: 'Musica originale', name: 'Vincenzo Carbotta' },
      { role: 'Makeup Artist', name: 'Alice Perchinelli' },
      { role: 'Costume supervisor & Hair Stylist', name: 'Pamela Gasparro' },
      { role: 'Runner', name: 'Emmanuele Carlone' },
      { role: 'Montaggio', name: 'Pietro Giocondo' },
      { role: 'Backstage', name: 'Rebecca Superbo' },
    ],
    backstageImages: [IMG(1200, 800), IMG(1200, 800), IMG(1200, 800), IMG(1200, 800)],
  },
];


